FROM localhost/steam-headless:labwc-wayland-nvidia

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        foot \
        fuzzel \
        labwc \
        waybar \
        wlr-randr \
        xwayland \
        avahi-daemon \
        seatd \
        flatpak \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

COPY overlay-labwc /

RUN chmod +x /usr/bin/start-labwc.sh /usr/bin/start-sunshine-labwc.sh \
    /usr/bin/start-steam-labwc.sh /usr/bin/install-bolt.sh \
    /usr/bin/display-control /usr/bin/display-menu \
    /etc/cont-init.d/99-configure_labwc.sh \
    /templates/home_directory_template/.config/labwc/autostart

ENV DESKTOP_SESSION="labwc" \
    WAYLAND_DISPLAY="wayland-0" \
    DISPLAY_SIZEW="2560" \
    DISPLAY_SIZEH="1600" \
    DISPLAY_REFRESH="120" \
    DISPLAY_SCALE="1.25" \
    ENABLE_STEAM="true" \
    WLR_BACKENDS="headless,libinput" \
    XDG_CURRENT_DESKTOP="labwc" \
    XDG_SESSION_TYPE="wayland"
